### ISSUE TITLE
Creación del subdominio

### ISSUE THREAD

**Issue by UriProtocol** [UriProtocol/Gonzalez_parcial3#11]
@ingreyeslara 
Nombre del subdominio: lasgorrasdgo
Servidor proporcionado por el profesor

**Comment by ingreyeslara** [comment]
listo
![gorra](https://github.com/user-attachments/assets/aaa99691-f790-448e-92de-fbffce14065a)
![gorra2](https://github.com/user-attachments/assets/9cc3a18a-7cf6-4621-915b-bc758e9e169f)
